<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'Utilities\\' => array($vendorDir . '/skyscanner/jsonpath/src/Skyscanner'),
    'UpdateHelper\\' => array($vendorDir . '/kylekatarnls/update-helper/src'),
    'Twig_' => array($vendorDir . '/twig/twig/lib'),
    'Sunra\\PhpSimple\\HtmlDomParser' => array($vendorDir . '/sunra/php-simple-html-dom-parser/Src'),
    'Smtpapi' => array($vendorDir . '/sendgrid/smtpapi/lib'),
    'Sabberworm\\CSS' => array($vendorDir . '/sabberworm/php-css-parser/lib'),
    'PurplePixie' => array($vendorDir . '/purplepixie/phpdns/src'),
    'PayPal' => array($vendorDir . '/paypal/rest-api-sdk-php/lib'),
    'Parsedown' => array($vendorDir . '/erusev/parsedown'),
    'Mockery' => array($vendorDir . '/mockery/mockery/library'),
    'Mailgun' => array($vendorDir . '/mailgun/mailgun-php/src'),
    'JsonPath\\' => array($vendorDir . '/skyscanner/jsonpath/src/Skyscanner'),
    'Doctrine\\ORM\\' => array($vendorDir . '/doctrine/orm/lib'),
    'Doctrine\\DBAL\\' => array($vendorDir . '/doctrine/dbal/lib'),
    'Doctrine\\Common\\Collections\\' => array($vendorDir . '/doctrine/collections/lib'),
    'Braintree' => array($vendorDir . '/braintree/braintree_php/lib'),
    'Acelle\\Extra' => array($vendorDir . '/louis/sendgrid/src'),
);
